export function securityGuardsResponseMapper(entity: any) {
  return {
    id: entity.id,
    guardId: entity.guardId,
    vendorId: entity.vendorId,
    dateOfBirth: entity.dateOfBirth,
    gender: entity.gender,
    emergencyContact: entity.emergencyContact,
    permanentAddress: entity.permanentAddress,
    currentAddress: entity.currentAddress,
    profilePhotoUrl: entity.profilePhotoUrl,
    idType: entity.idType,
    idNumber: entity.idNumber,
    idProofUrl: entity.idProofUrl,
    policeVerificationStatus: entity.policeVerificationStatus,
    backgroundCheckStatus: entity.backgroundCheckStatus,
    employeeCode: entity.employeeCode,
    joiningDate: entity.joiningDate,
    employmentType: entity.employmentType,
    designation: entity.designation,
    status: entity.status,
    metadata: entity.metadata,
    createdAt: entity.createdAt,
    createdBy: entity.createdBy,
    updatedAt: entity.updatedAt,
    updatedBy: entity.updatedBy,
  };
}